image: node:8.11.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g 
  - npm install hexo-generator-search --save
  - npm install 
  - hexo generate --deploy
  artifacts:
    paths:
    - public
  only:
  - developer
  tags:
  - linux