image: node:8.11.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g --registry http://registry.cnpmjs.org
  - npm install hexo-generator-search --save --registry http://registry.cnpmjs.org
  - npm install 
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - developer
  tags:
  - C7